### PR TITLE
Add "get_multiple_channel_values" and "set_multiple_channel_values" methods

### PR DESCRIPTION
**Pull request by jacobson3**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-python/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Adds following methods to niveristand.clientapi._workspace2._Workspace2 class
+ get_multiple_channel_values
+ set_multiple_channel_values

### Why should this Pull Request be merged?

I want to be able to get and set multiple channels at a time.

### What testing has been done?

Manually tested against VeriStand project. Looked for existing unit tests for getting and setting single channel values to copy but none existed.

### CODE REVIEW

**Comment by jacobson3** [comment]
@skolthay / @gahegde-ni Is there anything I need to change or add to this PR?

**Comment by skolthay** [comment]
> @skolthay / @gahegde-ni Is there anything I need to change or add to this PR?

Looks good to me, Thanks for the contribution!

**Comment by jacobson3** [comment]
@skolthay Thanks. I don't have the ability to merge PRs so if everything is good, someone from NI will have to do that.

**Comment by ashukumaNI** [comment]
@jacobson3 we already have existing API to that job. You refer to this [test file](https://github.com/ni/niveristand-python/blob/master/tests/legacy/test_legacy_calc_channel.py) as an example. 

In case of further doubt, you can tag me as well. 
By the way, thank you very much for your contribution.

**Comment by jacobson3** [comment]
> @jacobson3 we already have existing API to that job. You refer to this [test file](https://github.com/ni/niveristand-python/blob/master/tests/legacy/test_legacy_calc_channel.py) as an example.
> 
> In case of further doubt, you can tag me as well. By the way, thank you very much for your contribution.

@ashukumaNI I didn't realize this PR had been closed but not merged. I am aware that there was an existing way to do this but it only existing within the context of the legacy API. This update was to add the same functionality to the non-legacy interface.

**Comment by ashukumaNI** [comment]
> > @jacobson3 we already have existing API to that job. You refer to this [test file](https://github.com/ni/niveristand-python/blob/master/tests/legacy/test_legacy_calc_channel.py) as an example.
> > In case of further doubt, you can tag me as well. By the way, thank you very much for your contribution.
> 
> @ashukumaNI I didn't realize this PR had been closed but not merged. I am aware that there was an existing way to do this but it only existing within the context of the legacy API. This update was to add the same functionality to the non-legacy interface.

@jacobson3 we have plans to replace the legacy API. You will be able to use them without any issues. Until then, you can use the legacy one. Thanks!

**Pull request closed without merging**
